# -*- coding: utf-8 -*-
"""day 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10udACAh-nqYgBOT95ij7iZkg-t5wSHJJ
"""



"""day 4
assignment 1
"""

#the string
str = 'what we think we become ; we are python programer.'
 
#substring
substr = 'we'
 
#finding number of occurrences of substring in given string
count = str.count(substr)
 
print("Number of occurrences of substring :", count)

"""assignment 3"""

a = "Hello world!"
b = "hello 123"
c = "mynameisPeter"

print(a.islower())
print(b.islower())
print(c.islower())

a = "Hello World!"
b = "hello 123"
c = "MY NAME IS PETER"

print(a.isupper())
print(b.isupper())
print(c.isupper())